spring.application.name=Control1
server.port=6789
logging.file.name=Control1.log
spring.datasource.url=jdbc:postgresql://localhost:5432/remedio
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect